# Generated by Django 6.0 on 2026-01-01 06:18

import accounts.models
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_passwordresettoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[accounts.models.validate_image], verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='banner',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[accounts.models.validate_image], verbose_name='banner'),
        ),
    ]
