# Generated by Django 6.0 on 2026-01-02 22:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_avatar_alter_user_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='banner',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='banner'),
        ),
    ]
